### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by ghost** [general-ai-challenge/Round1#9]
Following the README.md  Linux installation, with 2.7 and 3.5 installed, the system Python being 3.5, the default Ubuntu configuration, following the git clone, and correcting the directory to /Round1, this is from terminal:

18:17:16  stephen@Aspire-V3  ~/PycharmProjects/Round1  ⬡    master ✔ 
$ pip install -r src/requirements/py2.txt
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip import main
  File "/usr/local/lib/python3.5/dist-packages/pip/__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/local/lib/python3.5/dist-packages/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
    @_call_aside
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3046, in _initialize_master_working_set
    dist.activate(replace=False)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2578, in activate
    declare_namespace(pkg)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2152, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2092, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2121, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'

**Comment by vlasy** [comment]
Hi,
you mention, that default Python is 3.5, however you install the requirements for Python 2 - correct installation for Python 3 is

`pip install -r src/requirements/py3.txt`

But your problems does not seem to be in the requirements but in the installation process itself. Have you tried googling the error `AttributeError: '_NamespacePath' object has no attribute 'sort'?` It might be a problem with `pip` or `setuptools`.

**Comment by ghost** [comment]
The bug report was't against 'pip', or the way it is used, Rather the bug report is against the wording of the installation instructions of this repository, README.md. I included the terminal output to save you time reproducing the bug, in the event the reason for it wasn't clear. I will include a direct reference to README.md instead of instructions in any future bug reports. 

Further the command as written in README.md will not work period. after cloning from git, your files are in /Round1 so the current:

"python src/run.py src/tasks_config.challenge.json -l learners.human_learner.ImmediateHumanLearner" 

Will not work because you are launching it from the wrong directory.

I'm not aware of any machine learning enthusiasts that don't have both 2.x and 3.x installed at system level or that instead access them via a conda like environment manager.

From the response to my PR with minor PEP8 corrections, it seems unsolicited PR's are actively discouraged, in the above case I was informed I would to need to refactor the entire code base in a single branch as a prerequisite for consideration, which is beyond what I'm prepared to commit to without any indication it's wanted, as I will soon report in another bug report. This code has never been run much less tested, there is a fatal type error on line 131 in run.py byte-value when str expected

**Comment by vlasy** [comment]
Thanks for the info, we fixed the README instructions. 

Can you try to install the requirements for your active version of Python and let us know if the problem persists?

**Comment by ghost** [comment]
@vlasy, thank-you for acknowledging an issue, any issue, as I've stated repeatably  on the other issues filed. I have stepped away from interacting further with this repository, with the exception of clarifying the original issue report. 

The current repository attitudes, procedures, and practices, make it a poor use on my time and the GoodAI employees time rejecting them, or giving their opinion of what labour units I owe to Facebook Inc, by notifying you of an issue.

**Comment by martinpoliak-goodai** [comment]
We're unable to reproduce the installation error; it's possible that it's related to an installation of py2.txt requirements in a python3 environment.
To my understanding, the rest of the issue is resolved so I am adding a "cannot reproduce" label and "low priority" for the pip install part.

**Comment by ghost** [comment]
You were unable to reproduce the error by following the instructions, yet you added a commit with the addition of a correction adding the change directory information, in which your commit had a new error, which I filled an issue for (as I am still linked to your repo as upstream), It was quickly patched here : https://github.com/general-ai-challenge/Round1/commit/10d8f58e3c9fb5c0821b896e0f384b0d26e5b035 

Why are you making false statements? Do you require more information related to the issue #9 report?

I did want to add if I note additional false statements related to my myself or my work, I will publicly rebut them, and take all steps required to have your statements removed.

**Comment by krisives** [comment]
How do I filter out issues related to a specific user? Github lets me look at issues by a specific author but I can't find a way to say "never show me an issue created by this user again"

**Comment by ghost** [comment]
If you consider   issue:author != stephenbhope  then 'forever' issue:author !=stephenbhope, logic doesn't change based on opinions :)

It will not be an issue here, you may want to preset filters for Ubuntu 17.04, Docker, Snapcraft, Amazon Web Services, etc
